package com.roseboard.infrastructure.message;

public enum MessageErrorCode {
    INVALID_ENVELOPE,
    INVALID_DESCRIPTOR,
    PAYLOAD_TOO_LARGE,
    HEADERS_TOO_LARGE,
    METADATA_TOO_LARGE,
    UNSUPPORTED_CONTENT_TYPE,
    UNKNOWN_SCHEMA,
    UNKNOWN_MESSAGE_TYPE,
    SCHEMA_VALIDATION,
    DUPLICATE_REGISTRATION,
    MISSING_DEFAULT_CODEC,
    UNSUPPORTED_ACCEPT,
    NATIVE_WIRE_NOT_GENERAL_CODEC
}
